cc_library(
    name = "PaymentMethod",
    srcs = ["PaymentMethod/PaymentMethod.cpp", 
            "CreditCard/CreditCard.cpp", 
            "PayPal/PayPal.cpp"],
    hdrs = ["PaymentMethod/PaymentMethod.hpp", 
            "CreditCard/CreditCard.hpp", 
            "PayPal/PayPal.hpp"],
    visibility = ["//:__pkg__"]
)
